---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkiday
  labels:
    app.kubernetes.io/name: checkiday
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: checkiday
  template:
    metadata:
      labels:
        app.kubernetes.io/name: checkiday
    spec:
      containers:
        - name: checkiday
          image: checkiday
          ports:
            - containerPort: 8080
              name: http
